# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e1391f9cadeb7268bc5fcd822540195a411acfb3771b8b434b7f67601f41f35ea92689aa5fe049f8a8507d9cea06db6b25f25333c0b49bec4aae96ff2429d5

test:
  secret_key_base: c76128a996cf04d5d05cddee5bd37dd89a7ca6992389207b5e1d223a23cfd6e3c32618f045803ea0d4095f94d86e39a46b56c6979eba4e82a240504be6f5cbb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
